- name: Check if ollama binary exists
  ansible.builtin.stat:
    path: /usr/local/bin/ollama
  register: ollama_stat
  changed_when: false
  failed_when: false

- name: Download ollama install script
  ansible.builtin.get_url:
    url: "{{ ollama_install_url }}"
    dest: "{{ tmp_downloads_dir }}/ollama.sh"
    mode: '700'
  when: not ollama_stat.stat.exists
  changed_when: false

- name: Run ollama install script
  ansible.builtin.command: "{{ tmp_downloads_dir }}/ollama.sh"
  when: not ollama_stat.stat.exists
  changed_when: false

- name: Install Open WebUI
  community.general.pipx:
    name: open-webui
    state: present
