# Create Neovim configuration directory
- name: Create nvim config directory
  ansible.builtin.file:
    path: "{{ kickstart_nvim_config_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '700'

# Clone Kickstart.nvim configuration if not already present
- name: Clone kickstart.nvim
  ansible.builtin.git:
    repo: "{{ kickstart_repo }}"
    dest: "{{ kickstart_nvim_config_dir }}"
    clone: true
    update: true
    version: master
  when: not (lookup('fileglob', kickstart_nvim_config_dir + '/*', errors='ignore'))
