# Kickstart.nvim Neovim configuration setup
- name: Include vars
  ansible.builtin.include_vars: ../vars/main.yml

# Create Neovim configuration directory
- name: Create nvim config directory
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/nvim"
    state: directory
    owner: "{{ local_user }}"
    group: "{{ local_user_gid }}"
    mode: '755'

# Clone Kickstart.nvim configuration
- name: Clone kickstart.nvim
  ansible.builtin.git:
    repo: 'https://github.com/nvim-lua/kickstart.nvim.git'
    dest: "{{ home_dir }}/.config/nvim"
    clone: true
    update: true
    version: master
