# Create Neovim configuration directory
- name: Create nvim config directory
  ansible.builtin.file:
    path: "{{ user_config_dir }}/nvim"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '700'

# Clone Kickstart.nvim configuration
- name: Clone kickstart.nvim
  ansible.builtin.git:
    repo: 'https://github.com/nvim-lua/kickstart.nvim.git'
    dest: "{{ user_config_dir }}/nvim"
    clone: true
    update: true
    version: master
  when: not (lookup('fileglob', '/home/kevin/.config/nvim/*', errors='ignore'))
