lazydocker_archive: "lazydocker_{{ lazydocker_version }}_Linux_x86_64.tar.gz"
lazydocker_extract_dir: "lazydocker_{{ lazydocker_version }}_Linux_x86_64"
lazydocker_download_url: "https://github.com/jesseduffield/lazydocker/releases/download/v{{ lazydocker_version }}/{{ lazydocker_archive }}"
