- name: Check if Starship binary is already installed
  ansible.builtin.stat:
    path: "{{ user_local_bin }}/starship"
  register: starship_stat

- name: Install Starship if not present
  when: not starship_stat.stat.exists
  block:
    - name: Get latest Starship version
      ansible.builtin.uri:
        url: "{{ starship_latest_version_url }}"
        return_content: true
      register: starship_api_response

    - name: Set Starship version fact
      ansible.builtin.set_fact:
        starship_version: "{{ starship_api_response.json.tag_name | regex_replace('^v', '') }}"

    - name: Download Starship tarball
      ansible.builtin.get_url:
        url: "{{ starship_download_url }}"
        dest: "{{ tmp_downloads_dir }}/starship.tar.gz"
        mode: '644'

    - name: Extract Starship binary
      ansible.builtin.unarchive:
        src: "{{ tmp_downloads_dir }}/starship.tar.gz"
        dest: "{{ tmp_extracts_dir }}/"
        remote_src: true

    - name: Install Starship binary to /usr/local/bin
      ansible.builtin.copy:
        src: "{{ tmp_extracts_dir }}/starship"
        dest: "{{ user_local_bin }}/starship"
        mode: '755'
        remote_src: true
