# Set system hostname
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

# Configure system timezone
- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ timezone }}"

# Generate and enable locales
- name: Generate locales
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ locales }}"

# Configure passwordless sudo for user (optional)
- name: Configure passwordless sudo
  become: true
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/99-{{ ansible_user_id }}-sudo-user"
    content: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD:ALL"
    mode: '440'
    validate: "/usr/sbin/visudo --check --file=%s"
  when: passwordless_sudo
