- name: Install Docker completions if docker is present
  ansible.builtin.command: docker completion fish
  register: docker_completion
  changed_when: false
  failed_when: false

- name: Write Docker completions to file
  ansible.builtin.copy:
    content: "{{ docker_completion.stdout }}"
    dest: "{{ fish_shell_config_dir }}/completions/docker.fish"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '644'
  when: docker_completion.stdout is defined and docker_completion.stdout|length > 0
