- name: Check if lazygit binary is already installed
  ansible.builtin.stat:
    path: "/usr/bin/lazygit"
  register: lazygit_binaries_stat

- name: Install lazygit if not present
  when: not lazygit_binaries_stat.stat.exists
  block:
    - name: Get latest lazygit version
      ansible.builtin.uri:
        url: "{{ lazygit_latest_version_url }}"
        return_content: true
      register: lazygit_api_response

    - name: Set lazygit version fact
      ansible.builtin.set_fact:
        lazygit_version: "{{ lazygit_api_response.json.tag_name | regex_replace('^v', '') }}"

    - name: Download lazygit binary if not present
      ansible.builtin.get_url:
        url: "{{ lazygit_download_url }}"
        dest: "{{ tmp_downloads_dir }}/{{ lazygit_archive }}"
        mode: '644'

    - name: Unarchive lazygit binary if not present
      ansible.builtin.unarchive:
        src: "{{ tmp_downloads_dir }}/{{ lazygit_archive }}"
        dest: "{{ tmp_extracts_dir }}"
        remote_src: true

    - name: Move lazygit binary to /usr/bin
      become: true
      ansible.builtin.copy:
        src: "{{ tmp_extracts_dir }}/lazygit"
        dest: "/usr/bin/lazygit"
        mode: '755'
        remote_src: true

- name: Symlink lazygit binary to {{ user_local_bin }}
  ansible.builtin.file:
    src: "/usr/bin/lazygit"
    dest: "{{ user_local_bin }}/lazygit"
    state: link
    force: true
