# Install GitHub CLI via official repository
- name: Install GitHub CLI
  become: true
  block:
    # Add GitHub CLI GPG key
    - name: Add GPG key
      ansible.builtin.apt_key:
        url: "{{ github_cli_keyring_url }}"
        state: present

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ github_cli_arch | default('amd64') }}] {{ github_cli_repo }} stable main"
        state: present
        filename: github-cli

    - name: Update cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install gh CLI
      ansible.builtin.apt:
        name: gh
        state: present
