# This role installs and configures the Fish shell for a user.
- name: Ensure Fish is installed
  ansible.builtin.apt:
    name: fish
    state: present
  become: true

- name: Ensure Fish config directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ fish_config_dir }}", mode: '700' }
    - { path: "{{ fish_config_dir }}/conf.d", mode: '700' }
    - { path: "{{ fish_config_dir }}/completions", mode: '700' }

- name: Copy xdg.fish config
  ansible.builtin.copy:
    src: files/xdg.fish
    dest: "{{ fish_config_dir }}/conf.d/xdg.fish"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '600'

- name: Add Fish to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ fish_path }}"
    state: present
  become: true

- name: Set Fish as default shell for user
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ fish_path }}"
  become: true
  when: fish_set_default_shell | bool

# Remove Fish greeting
- name: Remove Fish greeting
  ansible.builtin.shell: "set -U fish_greeting"
  args:
    executable: "{{ fish_path }}"
  changed_when: false
