- name: Check if lazydocker binary is already installed
  ansible.builtin.stat:
    path: "/usr/bin/lazydocker"
  register: lazydocker_binaries_stat

- name: Install lazydocker if not present
  when: not lazydocker_binaries_stat.stat.exists
  block:
    - name: Get latest lazygit version
      ansible.builtin.uri:
        url: "{{ lazydocker_latest_version_url }}"
        return_content: true
      register: lazydocker_api_response

    - name: Set lazygit version fact
      ansible.builtin.set_fact:
        lazydocker_version: "{{ lazydocker_api_response.json.tag_name | regex_replace('^v', '') }}"

    - name: Download lazydocker binary if not present
      ansible.builtin.get_url:
        url: "{{ lazydocker_download_url }}"
        dest: "{{ tmp_downloads_dir }}/{{ lazydocker_archive }}"
        mode: '0644'

    - name: Unarchive lazydocker binary if not present
      ansible.builtin.unarchive:
        src: "{{ tmp_downloads_dir }}/{{ lazydocker_archive }}"
        dest: "{{ tmp_extracts_dir }}"
        remote_src: true

    - name: Move lazydocker binary to /usr/bin
      become: true
      ansible.builtin.copy:
        src: "{{ tmp_extracts_dir }}/lazydocker"
        dest: "/usr/bin/lazydocker"
        mode: '755'
        remote_src: true

- name: Symlink lazydocker binary to {{ user_local_bin }}
  ansible.builtin.file:
    src: "/usr/bin/lazydocker"
    dest: "{{ user_local_bin }}/lazydocker"
    state: link
    force: true
