# Create user directories with proper permissions
- name: Create temporary and user directory structure
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  loop: "{{ create_dirs_list }}"
