# Create user directories with proper permissions
- name: Create user directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "{{ item.mode }}"
  with_items: "{{ create_dirs_list }}"
