# This role installs Docker via Snap and configures user access.
- name: Install and configure Docker via Snap
  become: true
  block:
    # Ensure snapd is installed
    - name: Ensure snapd is installed
      ansible.builtin.package:
        name: snapd
        state: present

    # Install Docker via Snap
    - name: Install Docker snap
      community.general.snap:
        channel: "{{ docker_snap_channel }}"
        name: docker
        state: present

    # Create docker group for user access
    - name: Ensure docker group exists
      ansible.builtin.group:
        name: "{{ docker_group_name }}"
        state: present

    # Add user to docker group for non-root Docker usage
    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ docker_user }}"
        groups: "{{ docker_group_name }}"
        append: true

    # Ensure Docker service is enabled and started
    - name: Ensure Docker service is enabled and started
      ansible.builtin.systemd:
        name: snap.docker.dockerd.service
        enabled: true
        state: started
