# Main playbook for Cosmic OS setup and configuration
- name: Setup Cosmic OS
  hosts: localhost
  roles:
    - name: internal_vars
      tags: [always]
    - name: create_dirs
      tags: [always]
  tasks:
    - name: Configure host settings
      ansible.builtin.include_role:
        name: host_config
        apply:
          tags: [host-config]
      when: enabled_roles.host_config
      tags: [host-config]

    - name: Manage system packages
      ansible.builtin.include_role:
        name: manage_packages
        apply:
          tags: [packages]
      when: enabled_roles.manage_packages
      tags: [packages]

    - name: Configure ufw firewall
      ansible.builtin.include_role:
        name: ufw
        apply:
          tags: [firewall]
      when: enabled_roles.ufw
      tags: [firewall]

    - name: Install Nerd Fonts
      ansible.builtin.include_role:
        name: nerd_fonts
        apply:
          tags: [nerd-fonts]
      when: enabled_roles.nerd_fonts
      tags: [nerd-fonts]

    - name: Install and configure fish shell
      ansible.builtin.include_role:
        name: fish_shell
        apply:
          tags: [fish]
      when: enabled_roles.fish_shell
      tags: [fish]

    - name: Add custom paths to Fish user paths
      ansible.builtin.include_role:
        name: fish_paths
        apply:
          tags: [fish]
      when: enabled_roles.fish_shell and enabled_roles.fish_paths
      tags: [fish]

    - name: Install Fisher and plugins
      ansible.builtin.include_role:
        name: fisher
        apply:
          tags: [fish]
      when: enabled_roles.fisher and enabled_roles.fish_shell
      tags: [fish]
    
    - name: Symlink fd and bat
      ansible.builtin.include_role:
        name: fish_symlinks
        apply:
          tags: [fish]
      tags: [fish]
      when: enabled_roles.fish_shell and enabled_roles.fish_symlinks

    - name: Install extra completions
      ansible.builtin.include_role:
        name: fish_completions
        apply:
          tags: [fish]
      tags: [fish]
      when: enabled_roles.fish_shell and enabled_roles.fish_completions

    - name: Install Starship prompt
      ansible.builtin.include_role:
        name: starship
        apply:
          tags: [starship]
      tags: [starship]
      when: enabled_roles.starship

    - name: Install fzf
      ansible.builtin.include_role:
        name: fzf
        apply:
          tags: [fzf]
      tags: [fzf]
      when: enabled_roles.fzf

    - name: Install and configure Docker
      ansible.builtin.include_role:
        name: docker
        apply:
          tags: [docker]
      when: enabled_roles.docker
      tags: [docker]

    - name: Install Kickstart
      ansible.builtin.include_role:
        name: kickstart
        apply:
          tags: [kickstart]
      when: enabled_roles.kickstart
      tags: [kickstart]

    - name: Install GitHub CLI
      ansible.builtin.include_role:
        name: github_cli
        apply:
          tags: [github-cli]
      when: enabled_roles.github_cli
      tags: [github-cli]

    - name: Install yadm and setup dotfiles
      ansible.builtin.include_role:
        name: yadm
        apply:
          tags: [yadm]
      when: enabled_roles.yadm
      tags: [yadm]

    - name: Install vim-plug
      ansible.builtin.include_role:
        name: vimplug
        apply:
          tags: [vimplug]
      when: enabled_roles.vimplug
      tags: [vimplug]

    - name: Install Ollama and Open WebUI
      ansible.builtin.include_role:
        name: ollama
        apply:
          tags: [ollama]
      when: enabled_roles.ollama
      tags: [ollama]

    - name: Install ripgrep-all
      ansible.builtin.include_role:
        name: ripgrep_all
        apply:
          tags: [ripgrep-all]
      when: enabled_roles.ripgrep_all
      tags: [ripgrep-all]

    - name: Install lazygit
      ansible.builtin.include_role:
        name: lazygit
        apply:
          tags: [lazygit]
      when: enabled_roles.lazygit
      tags: [lazygit]

    - name: Install lazydocker
      ansible.builtin.include_role:
        name: lazydocker
        apply:
          tags: [lazydocker]
      when: enabled_roles.lazydocker
      tags: [lazydocker]
