# Main playbook for Cosmic OS setup and configuration
- name: Setup Cosmic OS
  hosts: localhost
  tasks:
    - name: Create temporary and user directory structure
      ansible.builtin.include_role:
        name: create_dirs
        apply:
          tags: [always]
      tags: [always]

    - name: Configure host settings
      ansible.builtin.include_role:
        name: host_config
        apply:
          tags: [host-config]
      when: enable_host_config
      tags: [host-config]

    - name: Manage system packages
      ansible.builtin.include_role:
        name: manage_packages
        apply:
          tags: [packages]
      when: enable_manage_packages
      tags: [packages]

    - name: Configure ufw firewall
      ansible.builtin.include_role:
        name: ufw
        apply:
          tags: [firewall]
      when: enable_ufw
      tags: [firewall]

    - name: Install Nerd Fonts
      ansible.builtin.include_role:
        name: nerd_fonts
        apply:
          tags: [nerd-fonts]
      when: enable_nerd_fonts
      tags: [nerd-fonts]

    - name: Install and configure fish shell
      ansible.builtin.include_role:
        name: fish_shell
        apply:
          tags: [fish_shell, fish]
      tags: [fish_shell, fish]

    - name: Add custom paths to Fish user paths
      ansible.builtin.include_role:
        name: fish_paths
        apply:
          tags: [fish, fish_paths]
      tags: [fish, fish_paths]

    - name: Install Fisher and plugins
      ansible.builtin.include_role:
        name: fisher
        apply:
          tags: [fish, fisher]
      tags: [fish, fisher]

    - name: Install Starship prompt
      ansible.builtin.include_role:
        name: starship
        apply:
          tags: [fish, starship]
      tags: [fish, starship]

    - name: Install fzf
      ansible.builtin.include_role:
        name: fzf
        apply:
          tags: [fish, fzf]
      tags: [fish, fzf]

    - name: Symlink fd and bat
      ansible.builtin.include_role:
        name: fish_symlinks
        apply:
          tags: [fish, fish_symlinks]
      tags: [fish, fish_symlinks]

    - name: Install extra completions
      ansible.builtin.include_role:
        name: fish_completions
        apply:
          tags: [fish, fish_completions]
      tags: [fish, fish_completions]

    - name: Install and configure Docker
      ansible.builtin.include_role:
        name: docker
        apply:
          tags: [docker]
      when: enable_docker
      tags: [docker]

    - name: Install Kickstart
      ansible.builtin.include_role:
        name: kickstart
        apply:
          tags: [kickstart]
      when: enable_kickstart
      tags: [kickstart]

    - name: Install GitHub CLI
      ansible.builtin.include_role:
        name: github_cli
        apply:
          tags: [github-cli]
      when: enable_github_cli
      tags: [github-cli]

    - name: Install yadm and setup dotfiles
      ansible.builtin.include_role:
        name: yadm
        apply:
          tags: [yadm]
      when: enable_yadm
      tags: [yadm]

    - name: Install vim-plug
      ansible.builtin.include_role:
        name: vimplug
        apply:
          tags: [vimplug]
      when: enable_vimplug
      tags: [vimplug]

    - name: Install Ollama and Open WebUI
      ansible.builtin.include_role:
        name: ollama
        apply:
          tags: [ollama]
      when: enable_ollama
      tags: [ollama]

    - name: Install ripgrep-all
      ansible.builtin.include_role:
        name: ripgrep_all
        apply:
          tags: [ripgrep-all]
      when: enable_ripgrep_all
      tags: [ripgrep-all]

    - name: Install lazygit
      ansible.builtin.include_role:
        name: lazygit
        apply:
          tags: [lazygit]
      when: enable_lazygit
      tags: [lazygit]

    - name: Install lazydocker
      ansible.builtin.include_role:
        name: lazydocker
        apply:
          tags: [lazydocker]
      when: enable_lazydocker
      tags: [lazydocker]
